# Generated by Django 5.0.6 on 2024-06-09 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speurtochten', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeTocht',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_tocht', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Speurder', max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='speurtocht',
            name='title',
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer_text',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='extra_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='map_coords',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='marker',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='next_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='speurtochten.question'),
        ),
        migrations.AddField(
            model_name='question',
            name='possible_answer_1',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='possible_answer_2',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='possible_answer_3',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='possible_answer_4',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='route',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='starting_point',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speurtocht',
            name='descr_start_points',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speurtocht',
            name='img_1',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='speurtocht',
            name='img_2',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='speurtocht',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='speurtocht',
            name='no_of_questions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speurtocht',
            name='no_of_start_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speurtocht',
            name='price',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='speurtocht',
            name='stad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='speurtocht',
            name='start_point_map',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='speurtocht',
            name='total_distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='speurtocht',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='GelopenTocht',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_started', models.DateTimeField(blank=True, null=True)),
                ('time_finished', models.DateTimeField(blank=True, null=True)),
                ('first_question', models.IntegerField(blank=True, null=True)),
                ('last_answered', models.IntegerField(blank=True, null=True)),
                ('started', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=False)),
                ('paid_for', models.BooleanField(default=False)),
                ('gt_code', models.CharField(blank=True, max_length=20)),
                ('overview', models.TextField(blank=True, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=50, null=True)),
                ('speurtocht', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speurtochten.speurtocht')),
                ('player', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='speurtochten.player')),
            ],
        ),
        migrations.CreateModel(
            name='Vraag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True)),
                ('answered', models.BooleanField(default=False)),
                ('answer_correct', models.BooleanField(default=False)),
                ('gt_code', models.CharField(max_length=20, null=True)),
                ('gelopen_tocht', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speurtochten.gelopentocht')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speurtochten.question')),
            ],
        ),
    ]
